model: horizonlstm
dataset: contdataset

# training parameters
epochs: 10000
batch_size: 256
optimizer: adamw
learning_rate: 1.e-3
loss_function: gaussian
num_workers: 2

num_layers: 4
hidden_size: 200

# dataset parameters
train_path: data/test0
validation_path: data/test0

window: 1
horizon: 100

delta_p: False
compensate_error: False

save_iter: 200
