model: horizonlstm
dataset: lstmdataset

# training parameters
epochs: 400
batch_size: 512
optimizer: adamw
learning_rate: 1.e-2
loss_function: mate

num_layers: 4
input_size: 9
hidden_size: 6

on_track: True
use_mask: True

# dataset parameters
train_path: data/test0_filtered
test_path: data/test0_filtered

window: 50
horizon: 50

normalize: True
delta_p: True
include_pos: False
include_r: True
no_z: True
zero_position: False
mask_window: True
