model: horizonlstm
dataset: contdataset_ws

# training parameters
epochs: 10000
batch_size: 256
optimizer: adamw
learning_rate: 1.e-5
loss_function: mse

num_layers: 4
hidden_size: 200

# dataset parameters
train_path: data/putnam_ws
validation_path: data/putnam_ws

window: 1
horizon: 100

delta_p: False
