model: horizonlstm
dataset: lstmdataset

# training parameters
epochs: 400
batch_size: 1024
optimizer: adamw
learning_rate: 1.e-2
loss_function: mate

num_layers: 6
input_size: 11
hidden_size: 10

on_track: True
use_mask: True

# dataset parameters
train_path: data/test0_filtered
test_path: data/test0_filtered

window: 100
horizon: 100

normalize: True
delta_p: True
include_pos: True
include_r: True
no_z: True
zero_position: False
mask_window: True
